export const SAVE_REGISTER_FORM_DATA = 'SAVE_REGISTER_FORM_DATA';
export const CLEAR_REGISTER_FORM_DATA = 'CLEAR_REGISTER_FORM_DATA';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
