export const SAVE_REGISTER_FORM_DATA = 'SAVE_REGISTER_FORM_DATA';
export const CLEAR_REGISTER_FORM_DATA = 'CLEAR_REGISTER_FORM_DATA';

export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const BLOG_GET_REQUEST = 'BLOG_GET_REQUEST';
export const BLOG_GET_SUCCESS = 'BLOG_GET_SUCCESS';
export const BLOG_GET_FAILED = 'BLOG_GET_FAILED';

export const BLOG_ADD_REQUEST = 'BLOG_ADD_REQUEST';
export const BLOG_ADD_SUCCESS = 'BLOG_ADD_SUCCESS';
export const BLOG_ADD_FAILED = 'BLOG_ADD_FAILED';
